name: Meson

on:
  [push, pull_request]

jobs:
  nix-build-develop:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false

    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix develop --command meson setup build/ --buildtype=release -Dsystem="x86_64-linux"
    - run: nix develop --command meson compile -C build
